### ISSUE TITLE
Lisp Games Community?

### ISSUE THREAD

**Issue by subtiv** [samvv/racket-gaming#15]
Hi,

I was googeling and came by this page: http://lispgames.org/index.php/Main_Page
It's a community site for games developed in Lisp and/or it's dialects...

It might be worthwhile to get in touch with them?

**Comment by samvv** [comment]
As with the other issues, this is really old but I have finally managed to add mine to the list 😃

Actually, thinking of it a few years later, a sort of community for people who are just getting started with programming would be great ... need to think about it.

Although way to late ... thanks for letting me know!
